// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using dashboardKlinik.Data;

#nullable disable

namespace dashboardKlinik.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260921040632_AddAntrianKlinikTable")]
    partial class AddAntrianKlinikTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("dashboardKlinik.Models.ActivityLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int?>("EntityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.ToTable("ActivityLog");
                });

            modelBuilder.Entity("dashboardKlinik.Models.AntrianKlinik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Departemen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("JenisKelamin")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("TEXT");

                    b.Property<string>("Keluhan")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int?>("KunjunganId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NPK")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("TEXT");

                    b.Property<string>("NamaPasien")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("NomorAntrian")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("NomorUrut")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PasienId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Plant")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("StatusAntrian")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Tanggal")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("WaktuDaftar")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("WaktuDipanggil")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("WaktuSelesai")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("KunjunganId");

                    b.HasIndex("NPK");

                    b.HasIndex("PasienId");

                    b.HasIndex("StatusAntrian");

                    b.HasIndex("Tanggal");

                    b.ToTable("AntrianKlinik");
                });

            modelBuilder.Entity("dashboardKlinik.Models.KunjunganKlinik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Departemen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Diagnosa")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Dokter")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("JenisKelamin")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("TEXT");

                    b.Property<string>("Keluhan")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("NPK")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("NamaPasien")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("PasienId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Plant")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TanggalKunjungan")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NPK");

                    b.HasIndex("PasienId");

                    b.HasIndex("Status");

                    b.HasIndex("TanggalKunjungan");

                    b.ToTable("KunjunganKlinik");
                });

            modelBuilder.Entity("dashboardKlinik.Models.Pasien", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Departemen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("JenisKelamin")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("TEXT");

                    b.Property<string>("NPK")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("NamaPasien")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Plant")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TanggalTerdaftar")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Departemen");

                    b.HasIndex("NPK")
                        .IsUnique();

                    b.HasIndex("NamaPasien");

                    b.HasIndex("Plant");

                    b.ToTable("Pasien");
                });

            modelBuilder.Entity("dashboardKlinik.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NPK")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TanggalDibuat")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NPK");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("dashboardKlinik.Models.AntrianKlinik", b =>
                {
                    b.HasOne("dashboardKlinik.Models.KunjunganKlinik", "Kunjungan")
                        .WithMany()
                        .HasForeignKey("KunjunganId");

                    b.HasOne("dashboardKlinik.Models.Pasien", "Pasien")
                        .WithMany()
                        .HasForeignKey("PasienId");

                    b.Navigation("Kunjungan");

                    b.Navigation("Pasien");
                });

            modelBuilder.Entity("dashboardKlinik.Models.KunjunganKlinik", b =>
                {
                    b.HasOne("dashboardKlinik.Models.Pasien", "Pasien")
                        .WithMany("Kunjungan")
                        .HasForeignKey("PasienId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Pasien");
                });

            modelBuilder.Entity("dashboardKlinik.Models.Pasien", b =>
                {
                    b.Navigation("Kunjungan");
                });
#pragma warning restore 612, 618
        }
    }
}
